### ISSUE TITLE
Merge reginii autonome de transport URL data and create a wiki for it

### ISSUE THREAD

**Issue by mnemonicflow** [gov-ithub/info-transport#29]
Merge rat.txt file from https://github.com/gov-ithub/info-transport/tree/master/docs
with Regii Autonome Romania.txt
from https://github.com/gov-ithub/info-transport-api/tree/c25ae164a259bde775f062712c13601c0b53153d/data (created by Ionut Ciuca)

**Comment by alexandru-calinoiu** [comment]
And then move them to wiki https://github.com/gov-ithub/info-transport/issues/28

**Comment by kagix** [comment]
Fac merge diseara.

**Comment by kagix** [comment]
Done
